spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/pivotseoul}
    username: ${SPRING_DATASOURCE_USERNAME:pivotseoul}
    password: ${SPRING_DATASOURCE_PASSWORD:pivotseoul}

  jpa:
    hibernate:
      ddl-auto: update
