FROM node:20-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --omit=dev

FROM node:20-alpine AS builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
RUN mkdir -p public && npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup -S pivotseoul && adduser -S pivotseoul -G pivotseoul

COPY --from=builder /app/public ./public
COPY --from=builder --chown=pivotseoul:pivotseoul /app/.next/standalone ./
COPY --from=builder --chown=pivotseoul:pivotseoul /app/.next/static ./.next/static

USER pivotseoul
EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"
CMD ["node", "server.js"]
